### PR TITLE
Geocode/places auto-complete list: improve selection results:

### LINKED ISSUE #39: 🐛 Bug -- geocode locations missing
#### Bug description

Not really a bug but some locations are not appearing in the geocode search. 

#### How to reproduce the problem

Enter “ocean grove, nj” into the location search in the symptoms form. 

### Resolution

Adjust the [scope of the google maps api](https://developers.google.com/places/supported_types#table3) we are using. Currently it’s set to “cities”, which does include townships, but not ones like ocean grove evidently. So the scope just needs to be widened a bit.

### PR DESCRIPTION
**Pull request by abettermap**
## Summary

We had some issues with geocoding when we switched to a setup that did not allow countries. So, now: fetch all non-business locations but then filter out things we don't want (e.g. country, state, county) before the user has a chance to see them. This should prevent entries like "Canada" as well as too-specific ones like street addresses.

## Issues resolved by this pull request

- Fixes #39

## Review type

|  **Type**  | **Required (Y/N)** |             **Instructions**             |
| :--------: | :----------------: | :--------------------------------------: |
| `Deployed` |        Y         |   Click link near `Deployed to` below.   |
|  `Local`   |        N         | Check out this branch, run its start cmd |
|  `GitHub`  |        N         |     Review diffs and likely Markdown     |

## Issue-specific review items

- [x] All checkboxes in the issue/s mentioned have been completed.
- [x] The issue/s in this request have been resolved.

### To test:

- [x] You _cannot_ enter a country, state, or county
- [x] You _can_ enter "Ocean Grove" (New Jersey) 
- [x] ...and any standard cities that you could already enter.
- [x] Your submission is added correctly to the DB.

### Errors

- [x] **Front-end:** no DevTools console errors occur in the built code (PR review URL) in the step/s required to test the PR.

### CODE REVIEW

**Comment by abettermap** [comment]
FYI I used [this list](https://developers.google.com/maps/documentation/geocoding/intro#Types) to determine what to fetch and what to then filter client-side.

**Comment by abettermap** [comment]
@Covid-Self-report-Tool/contributors I'm still not sure why Amplify Previews stopped working. I tried re-connecting the repo, removing the webhook, adding the Previews back, pushing to new branches, creating new PRs. No love. 😞

**Comment by abettermap** [comment]
@ajsamra I'll pass this one to you as well, please take a look when you have a chance and let me know if you have questions.

**Comment by ajsamra** [comment]
@abettermap no worries about amplify previews not working. It's very quick to just checkout the branch and test locally.

**Pull request merged**
